# Generated by Django 3.2.5 on 2021-07-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
