# Generated by Django 3.2.5 on 2021-07-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Image_upload', '0002_image_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
